# Generated by Django 5.1.6 on 2025-04-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop1_name', models.CharField(default='Wheat', max_length=100)),
                ('crop2_name', models.CharField(default='Corn', max_length=100)),
                ('crop1_profit', models.FloatField(default=5000)),
                ('crop2_profit', models.FloatField(default=6000)),
                ('total_land', models.FloatField(default=10)),
                ('crop1_land', models.FloatField(blank=True, null=True)),
                ('crop2_land', models.FloatField(blank=True, null=True)),
                ('labor_available', models.FloatField(default=32)),
                ('crop1_labor', models.FloatField(default=2)),
                ('crop2_labor', models.FloatField(default=4)),
                ('water_available', models.FloatField(default=5000)),
                ('crop1_water', models.FloatField(default=1000)),
                ('crop2_water', models.FloatField(default=500)),
                ('max_profit', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
    ]
